### ISSUE TITLE
Fix CSS/CGI paths when using Live in non-root dir (experimental)

### ISSUE THREAD

**Issue by kietcallies** [MS3FGX/Bluelog#5] opened 2015-05-25 14:40 UTC
When I try running the latest version, Bluelog Live wants to download the cgi rather than display the contents of cgi. I am able to run Bluelog Live using the old www folder from version 1.1.2 without any issues.

Bluelog Version: 1.1.3-dev

**Comment by MS3FGX** [comment] 2015-05-27 01:12
Can't seem to reproduce here.

What web server are you running? What does your configuration file look like? Are you trying to run Live out of the root /www directory, or something else?

**Comment by MS3FGX** [comment] 2016-04-21 20:32
Nobody else seems to be having this problem and I can't reproduce it on my end, so I'm going to close this. If anyone else has similar issues, please let me know.

**Closed by MS3FGX** 2016-04-21 20:32 UTC
